name: Deploy

on:
  workflow_run:
    workflows: Build    # Execute build workflow prior to this one
    branches: main      # Only deploy main branch to production
    types: completed

jobs:
  deploy:
    # `if` required because a workflow run is triggered regardless of
    # the result of the previous workflow (see the documentation page)
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # ... your implementation to deploy your project
    - name: deploy to AWS
      run: exit 0
