name: Deploy Stage

on:
  workflow_run:
    workflows: [Build]      # Execute build workflow prior to this one
    branches: [develop]     # Only run when develop branch
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: install cdk dependencies
        working-directory: ./cdk
        run: npm install

      - name: build deploy script
        working-directory: ./cdk
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: 
      name: stage
    steps:
      - name: cdk deploy backend
        working-directory: ./cdk
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'GGS-backend-test'
          cdk_args: '--require-approval never --context env=test --outputs-file ../ggs-frontend/src/config.json'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-2'
