name: Deploy

on:
  workflow_run:
    workflows: Build    # Execute build workflow prior to this one
    branches: main      # Only deploy main branch to production
    types: completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: deploy to AWS
        run: exit 0
