name: Deploy Production

on:
  workflow_run:
    workflows: [Build]      # Execute build workflow prior to this one
    branches: [main]        # Only run when main branch
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: succeed
        run: exit 0
