name: Deploy Stage

on:
  push:
    branches:
      - 'develop'  # Only run on develop branch and no other

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: stage       # Ties back to environment name configured in github repo | settings | environments
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: install backend dependencies
        working-directory: ./ggs-backend
        run: npm install

      - name: install backend resources dependencies
        working-directory: ./ggs-backend/resources/ggsLambda
        run: npm install

      - name: build backend
        working-directory: ./ggs-backend
        run: npm run build

      - name: run backend tests
        working-directory: ./ggs-backend/resources/ggsLambda
        run: npm test

      - name: install frontend dependencies
        working-directory: ./ggs-frontend
        run: npm ci

      - name: build frontend
        working-directory: ./ggs-frontend
        env:
          CI: false         # CI=true makes react build fail on warnings
        run: npm run build

      - name: run frontend tests
        working-directory: ./ggs-frontend
        run: npm test

      - name: install cdk dependencies
        working-directory: ./cdk
        run: npm install

      - name: build cdk deploy script
        working-directory: ./cdk
        run: npm run build

      # Note that the backend outputs a file with the various endpoints used by the frontend
      - name: cdk deploy backend
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'GGS-backend-test'
          cdk_args: '--require-approval never --context env=test --outputs-file ../ggs-frontend/src/config.json'
          actions_comment: false
          working_dir: 'cdk'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-2'

      - name: cdk deploy frontend
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'GGS-frontend-test'
          cdk_args: '--require-approval never --context env=test'
          actions_comment: false
          working_dir: 'cdk'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-2'
